---
php_apt_repositories: "ppa:ondrej/php"
php_pgp_key: ''
httpd_service: apache2
apache_user: www-data

web_conf_path: /etc/apache2/sites-available/000-default.conf
ssl_web_conf_path: /etc/apache2/sites-available/default-ssl.conf
#